config/routes.rb
Rails.application.routes.draw do
  devise_for :users

     resources :home do
       collection do
         get 'new_file'
         post 'filecreate'
         get 'details'
         get 'about'
       end
     end
   match 'contact_us'  => 'home#contact_us' , :via => [:get,:post], as: :contact_us_home_index

  root to: "home#index"
end

app/models/contact_u.rb
class ContactU < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base
  
  mount_uploader :file, FileUploader
  
  belongs_to :user
  CATEGORIES= ["Home", "Bath Room", "Bed Room" , "Drowing Room"]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
       
   has_many :images, :dependent => :destroy
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  #  layout :application
  
  def index
    @images = Image.all.group("category")
  end
  
  #open new video view page
  def new_file
    @image = Image.new(params[:image])
  end
  
  #save new video
  def filecreate
    begin
      @video = current_user.images.create!(params_image)
      flash[:alert] = "Image upload has been save successfully."
    rescue Exception => e
      p "Image upload is not save successfully.Please try again! Error -> #{e.message}"
      flash[:alert] = "Image upload is not save successfully.Please try again! Error -> #{e.message}"
    end
    redirect_to new_file_home_index_path
  end
  
  def details
    @images = Image.where(:category=> params[:category])
  end
  
  def contact_us
    
    if request.post?
      @contact= ContactU.new(contact_params)
      begin
        @contact.save!
        if @contact.present?
          name = params[:contact_us][:name]
          email = params[:contact_us][:email]
          phone = params[:contact_us][:phone]
          info = params[:contact_us][:info]
#          PerentsMailer.email_us(@contact).deliver_now
        end
        flash[:notice] = "Thank you for giving us your time. We will contact you very soon."
      rescue Exception => e
        flash[:alert] = "Contact email cannot be sent.Please try again! Error -> #{e.message}"
        p "--------------------------------   #{e.message}"
        
      end
      redirect_to contact_us_home_index_path
    end
    
    if current_user.present?
      @contacts= ContactU.all      
    end
    
  end
  
  def about
    
  end
  
  private
  
  def params_image
    params.require(:image).permit!
  end

  def contact_params
    params.require(:contact_us).permit(:name,:email,:phone,:info)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="main">
  <div class="featured_content" id="feature">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
        </div>
        &nbsp;&nbsp;&nbsp;
        <p style="text-align: center; color: red;"> Page under construction!</p>
      </div>
    </div>
  </div>
</div>

app/views/home/contact_us.html.erb
<script>
  $("#yKangID").removeClass("active");
  $("#DaycareID").removeClass("active");
  $("#ParentID").removeClass("active");
  $("#BlogID").removeClass("active");
  $("#WhatWeDoID").removeClass("active");
  $("#ContactUsID").addClass("active");
</script> 
<div class="container">
  <% if !current_user.present? %>
  <div class="jumbotron"></div>
  <div class="col-md-5">
    <h2>Contact Info</h2>
    <p>Works-  Contact Somenath Dey at mob no, or email somnath4ux@gmail.com</p>
    <div class="clearfix">&nbsp;</div>
    <p>Support- Contact Support at mob no, or email jahera4ux@gmail.com</p>
    <div class="clearfix">&nbsp;</div>
  </div>
  <div class="col-md-7">
    <h2>Get in Touch with Us</h2>
    
    <%= form_for :contact_us,:url => contact_us_home_index_path,:html => {:id => 'formID'}, :method => :post do |f|  %>
      <div class="controls">
        <%= f.text_field:name,autofocus: true ,:placeholder=>"Name",:class=>"validate[required] form-control"%>
        <p class="help-block"></p>
      </div>
      <div class="controls">
        <%= f.text_field:phone,autofocus: true ,:placeholder=>"Phone No.", :class=>"validate[required] form-control" ,maxlength: "14"%>
        <p class="help-block"></p>
      </div>
      <div class="controls">
        <%= f.email_field:email,autofocus: true ,:placeholder=>"Email", :class=>"validate[required,custom[email]] form-control" %>
        <p class="help-block"></p>
      </div>
      <div class="controls">
        <%= f.text_area:info,autofocus: true,:placeholder=>"Message",:rows=>"8", :cols=>"100",:id=>"message", :class=>"validate[required] form-control" %>
      </div>
      <div style="float:right; margin:10px 0">
        <%= f.submit "Send Message" , id: "btn-contact" , class: "btn btn-primary"%>  
        </div>
      <%end%>
    
  </div>
  <%else%>
  <h2 style="text-align: center;">Get in Touch with Us</h2>
  <div style="clear: both;">&nbsp;</div>
  <table class="table table-responsive table-condensed table-hover" id="datatable">
        <thead class="bg-purple">
          <tr>
            <th>Name</th>
            <th>Mobile No</th>
            <th>Email</th> 
            <th>Description</th>
            <th>Date</th>
            <th style=" text-align: center">Action</th>
          
        </tr>
      </thead>
      <% @contacts.each do |cont| %>
        <% @contact = cont.created_at %>
        <tr>
          <td><%= cont.name %></td> 
          <td><%= cont.phone %></td>
          <td><%= cont.email %></td>
          <td><%= cont.info %></td> 
          <td><%= @contact.strftime('%B %d  %Y') %> (<%=time_ago_in_words(@contact)+" "+"ago"%>)</td>
          <td style="text-align:center;">
            <span><%#= link_to 'Show', blog %></span>
            <span><%#= link_to 'Edit', edit_blog_path(blog) %></span>
            <span><%#= link_to 'Delete', blog, method: :delete, data: { confirm: 'Are you sure?' } %></span>
          </td>
        </tr>
      <% end %>

    </table>
  
  
  <%end%>
  
  
</div>
<div class=" clearfix"></div>
<div style="height: 30px">&nbsp;</div>


<script type="text/javascript">
  jQuery(document).ready(function() {
    var separator = '-'
    $('#contact_phone').keyup(function() {
      this.value = this.value.replace(/(\d{3})(\d{3})(\d{4})/, '(' + '$1' + ')' + ' ' + '$2' + separator + '$3');
    });
    $("#btn-contact").click(function() {
      $("#formID").validationEngine();
    });
  });
</script>

app/views/home/details.html.erb
<div class="main">
  <div class="featured_content" id="feature">
    <div class="container">
      <div class="row">
        <% @images.each do |image| %>
          <div class="col-lg-3 col-md-4 col-xs-6 thumb">
              <%= image_tag(image.file_url(:thumb),:class=>"thumbnail") if image.present?  %>
              <!--<img class="img-responsive" src="http://placehold.it/400x300" alt="">-->
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">         
      <div class="modal-body">                
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<style>
  ul {         
    padding:0 0 0 0;
    margin:0 0 0 0;
  }
  ul li {     
    list-style:none;
    margin-bottom:25px;           
  }
  ul li img {
    cursor: pointer;
  }
  .modal-body {
    padding:5px !important;
  }
  .modal-content {
    border-radius:0;
  }
  .modal-dialog img {
    text-align:center;
    margin:0 auto;
  }
  .controls{          
    width:50px;
    display:block;
    font-size:11px;
    padding-top:8px;
    font-weight:bold;          
  }
  .next {
    float:right;
    text-align:right;
  }
  /*override modal for demo only*/
  .modal-dialog {
    max-width:500px;
    padding-top: 90px;
  }
  @media screen and (min-width: 768px){
    .modal-dialog {
      width:500px;
      padding-top: 90px;
    }          
  }
  @media screen and (max-width:1500px){
    #ads {
      display:none;
    }
  }
</style>

app/views/home/index.html.erb
<!--start-->
<div style="width:1000px;margin-left: 80px;">
  <div id="ninja-slider" style="float:left;">
    <div class="slider-inner">
      <ul>
        <li><a class="ns-img" href="<%= asset_path "1.jpg"%>"></a></li>
        <li><a class="ns-img" href="<%= asset_path "2.jpg"%>"></a></li>
        <li><a class="ns-img" href="<%= asset_path "3.jpg"%>"></a></li>
        <li><a class="ns-img" href="<%= asset_path "4.jpg"%>"></a></li>
        <li><a class="ns-img" href="<%= asset_path "5.jpg"%>"></a></li>
        <li><a class="ns-img" href="<%= asset_path "6.jpg"%>"></a></li>
        <li><a class="ns-img" href="<%= asset_path "7.jpg"%>"></a></li>
        <li><a class="ns-img" href="<%= asset_path "8.jpg"%>"></a></li>
        <li><a class="ns-img" href="<%= asset_path "9.jpg"%>"></a></li>
        <li><a class="ns-img" href="<%= asset_path "10.jpg"%>"></a></li>
        <li><a class="ns-img" href="<%= asset_path "11.jpg"%>"></a></li>
        <li><a class="ns-img" href="<%= asset_path "12.jpg"%>"></a></li>
      </ul>
      <div class="fs-icon" title="Expand/Close"></div>
    </div>
  </div>
  <div id="thumbnail-slider" style="float:left;">
    <div class="inner">
      <ul>
        <li>
          <a class="thumb" href="<%= asset_path "1.jpg"%>"></a>
        </li>
        <li>
          <a class="thumb" href="<%= asset_path "2.jpg"%>"></a>
        </li>
        <li>
          <a class="thumb" href="<%= asset_path "3.jpg"%>"></a>
        </li>
        <li>
          <a class="thumb" href="<%= asset_path "4.jpg"%>"></a>
        </li>
        <li>
          <a class="thumb" href="<%= asset_path "5.jpg"%>"></a>
        </li>
        <li>
          <a class="thumb" href="<%= asset_path "6.jpg"%>"></a>
        </li>
        <li>
          <a class="thumb" href="<%= asset_path "7.jpg"%>"></a>
        </li>
        <li>
          <a class="thumb" href="<%= asset_path "8.jpg"%>"></a>
        </li>
        <li>
          <a class="thumb" href="<%= asset_path "9.jpg"%>"></a>
        </li>
        <li>
          <a class="thumb" href="<%= asset_path "10.jpg"%>"></a>
        </li>
        <li>
          <a class="thumb" href="<%= asset_path "11.jpg"%>"></a>
        </li>
        <li>
          <a class="thumb" href="<%= asset_path "12.jpg"%>"></a>
        </li>
      </ul>
    </div>
  </div>
  <div style="clear:both;"></div>
</div>&nbsp;
<div class="main">
  <div class="featured_content" id="feature">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
        </div>
        <% @images.each do |image| %>
          <div class="col-lg-3 col-md-4 col-xs-6 thumb">
            <a class="thumbnail" href="<%= details_home_index_path(:category=>image.category) %>">
  <%#= image_tag(image.file_url(:thumb)) if image.present? %>
              <!--<img class="img-responsive" src="http://placehold.it/400x300" alt="">-->
            </a>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/home/new_file.html.erb
<div class="container">
  <div class="col-md-7">
    <h2>Upload New Image</h2>
    <%= form_for :image, url: filecreate_home_index_path,html: {multipart: true , method: 'post'} do |f| %>
      <div class="controls">
        <label for="exampleInputEmail1">Select Category</label>
        <%= f.select :category, options_for_select(Image::CATEGORIES), {}, {:class => "validate[required] form-control"}%>
        <p class="help-block"></p>
      </div>
      <div class="controls">
        <label for="exampleInputEmail1">Title</label>
        <%= f.text_field :title, autofocus: true ,class: "validate[required] form-control", id:"exampleInputname" , placeholder:"Tile"%>
          <p class="help-block"></p>
        </div> 
        <div class="controls">
          <label for="exampleInputPassword1">Description</label>
          <%= f.text_area :desc, autofocus: true ,class: "validate[required] form-control", rows: "3", id:"exampleInputname" , placeholder:"Description"%>
            <p class="help-block"></p>
          </div> 

          <div class="controls">
            <label for="exampleInputFile">Video Input</label>
            <%= f.file_field :file , class: 'validate[required]'%>
              <p class="help-block"></p>
            </div> 


            <div style="float:left; margin:10px 0">
              <%= f.submit "Submit" , id: "btn-contact" , class: "btn btn-primary"%>  
              </div>
            <%end%>
            
          </div>
        </div>

        <div class=" clearfix"></div>
        <div style="height: 30px">&nbsp;</div>

app/views/home/show.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "show.html" %>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <title>InteriorApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="header">
      <div class="container">
        <div class="logo"> <a href="/">Logo</a> </div>
        <div class="menu"> <a class="toggleMenu" href="#"><img src="/assets/nav_icon.png" alt="" /> </a>
          <ul class="nav" id="nav">
            <li class="current"><a href="/">Home</a></li>
           <li><%= link_to "About" ,  about_home_index_path , method: 'GET' %></li>
            <li><a href="#">Blog</a></li>
            <li><%= link_to "Contact", contact_us_home_index_path, method: 'GET' %></li>
            <%if current_user%> 
              <li><%= link_to "Log out", destroy_user_session_path, method: 'DELETE' %></li>
              <li><%= link_to "New Image", new_file_home_index_path , method: 'GET'%></li>
            <%else%>
              <li><%= link_to "Log in", new_user_session_path %></li>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
            <% end -%>
            <!--<li class="btn-group" role="group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                     Dropdown
                        <span class="caret"></span>
                </button>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Dropdown link</a></li>
                        <li><a href="#">Dropdown link</a></li>
                    </ul>
            </li>-->
            <div class="clear"></div>
          </ul>
          <script type="text/javascript" src="js/responsive-nav.js"></script> 
        </div>
        <div class="clearfix"> </div>
      </div>
    </div>
     <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <div class="footer">      
      <div class="footer_bottom">
        <div class="copy">
          <p>Copyright &copy; 2016. All right reserved.</p>
        </div>
      </div>
    </div>
  </body>
</html>